---

# Copyright 2021 Cloudera, Inc. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# https://docs.cloudera.com/management-console/cloud/requirements-gcp/topics/mc-gcp_apis.html
- name: Ensure Google Services Enabled
  when: plat__gcp_enable_services | bool
  block:
    - name: Fetch list of enabled GCP Services
      command: >
        gcloud services list --enabled --project {{ plat__gcp_project }}
      register: __gcp_services_info

    - name: Determine list of missing Services
      set_fact:
        __plat_gcp_services_to_enable: "{{ __plat_gcp_services_to_enable | default([]) + ([__gcp_service_item] if __gcp_service_item not in __gcp_services_info.stdout else []) | unique }}"
      loop: "{{ plat__gcp_required_services }}"
      loop_control:
        loop_var: __gcp_service_item

    - name: Enable missing GCP Service APIs
      when: __plat_gcp_services_to_enable | length > 0
      command: >
        gcloud services enable --quiet {{ __gcp_enable_item }}
      loop: "{{ __plat_gcp_services_to_enable }}"
      loop_control:
        loop_var: __gcp_enable_item
